import pygame

pygame.init()

WIDTH, HEIGHT = RES = (810, 810)
FPS = 60
GRID_SIZE = 3
TILE = WIDTH // GRID_SIZE
FONT_SIZE = 600
FONT = pygame.font.Font(None, FONT_SIZE)

# Menu
BUTTON_SPACING = 15
BUTTON_HEIGHT = 70
BUTTON_WIDTH = 250
MENU_FONT = pygame.font.Font(None, 30)
MENU_FONT_SIZE = 30
MENU_FONT_COLOR = '#e0e1dd'
BUTTON_COLOR_SELECTED = '#415a77'
BUTTON_COLOR = '#778da9'
BUTTON_COLOR_BORDER = '#1b263b'
MATCHING_RED = '#BC4749'
PVP = 0
PVA = 1
EXIT = 2