import pygame

pygame.init()

WIDTH, HEIGHT = RES = (810, 810)
FPS = 60
GRID_SIZE = 3
TILE = WIDTH // GRID_SIZE
FONT_SIZE = 600
FONT = pygame.font.Font(None, FONT_SIZE)

# Menu
BUTTON_SPACING = 15
BUTTON_HEIGHT = 70
BUTTON_WIDTH = 250
MENU_FONT = pygame.font.Font(None, 30)
MENU_FONT_SIZE = 30
MENU_FONT_COLOR = '#F2E8CF'
BUTTON_COLOR_SELECTED = '#A7C957'
BUTTON_COLOR = '#6A994E'
BUTTON_COLOR_BORDER = '#386641'
MATCHING_RED = '#BC4749'
PVP = 0
PVA = 1
